
== Use-Case: Rabatt berechnen
===	Kurzbeschreibung
Das System gibt pro Kundenkonto ab einem Umsatz von 25€ einen dauerhaften Rabatt in höhe von 10%

===	Kurzbeschreibung der Akteure

==== Nutzer
Der Nutzer kann seinen Rabattstatus einsehen.

==== System
Im System wird der Umsatz gezählt und ab 25€ Umsatz ein Rabatt in höhe von 10% aktiviert

=== Vorbedingungen
*   Es wird ein Kundenkonto benötigt, um die Rabattierung eindeutig zuzuordnen.
*   Im System muss der erbrachte Umsatz gezählt und für jedes Kundenkonto einzeln gespeichert werden.

=== Standardablauf (Basic Flow)
.	Der Ablauf beginnt mit dem Eingang eines Druckauftrags
.   Es wird überprüft ob für dieses Kundenkonto ein Anspruch auf die Rabattierung besteht
.   Wenn kein Anspruch besteht werden die Kosten des Druckjobs normal berechnet
.   Sobald die UNIdruckerei die Abholung und Bezahlung des Druckjobs bestätigt wird der erbrachte Umsatz dem Umsatzcounter des Kundenkontos gutgeschrieben

=== Alternative Abläufe
*   Wenn im Schritt 3. ein Anspruch besteht werden die Kosten mit dem Rabattfaktor verrechnet. Eine weitere Speicherung des erbrachten Umsatzes findet nicht statt.

=== Wesentliche Szenarios

==== Nutzer A gibt einen Druckauftrag mit einem Umsatz von 5€ in Auftrag. 
*   Der Druckjob wird erstellt und die Kosten werden standartmäßig berechnet. Die Abholung wird von der UNIdruckerei bestätigt. Der erbrachte Umsatz wird dem Kundenkonto von Nutzer A gutgeschrieben. Der Umsatzcounter von Nutzer A bleibt unter der Grenze von 25€. Der Rabatt wird für Nutzer A nicht freigeschalten.  

==== Nutzer B gibt einen Druckauftrag mit einem Umsatz von 5€ in Auftrag.  
*   Der Druckjob wird erstellt und die Kosten werden standartmäßig berechnet. Die Abholung wird von der UNIdruckerei bestätigt. Der erbrachte Umsatz wird dem Kundenkonto von Nutzer B gutgeschrieben. Der Umsatzcounter von Nutzer B überschreitet die Grenze von 25€. Der Rabatt wird für Nutzer B freigeschalten.  

==== Nutzer C gibt einen Druckauftrag mit einem Umsatz von 5€ in Auftrag.  
*   Der Druckjob wird erstellt und die Kosten werden standartmäßig berechnet. Die Abholung wird von der UNIdruckerei nicht bestätigt. Der erbrachte Umsatz wird dem Kundenkonto von Nutzer C nicht gutgeschrieben. 

==== Nutzer D gibt einen Druckauftrag mit einem Umsatz von 5€ in Auftrag. 
*   Nutzer D hat bereits über 25€ Umsatz erbracht. Der Druckjob wird erstellt und die Kosten werden unter beachtung des Rabattes in höhe von 10% berechnet. Eine weitere Speicherung des erbrachten Umsatzes findet nicht statt.


=== Nachbedingungen
*   Der Umsatzcounter des entsprechenden Kundenkontos wurde um den erbrachten Umsatz erhöht
*   Der Rabatt wird entsprechend des Umsatzcounters gegeben oder nicht gegeben
