
== Use-Case: Stornierung durch Uni-Druckerei
===	Kurzbeschreibung
Die UNIdruckerei hat die Möglichkeit den vom Nutzer erstellten Druckauftrag zu stornieren und somit das Drucken des Dokuments zu verhindern.

===	Kurzbeschreibung der Akteure

==== Nutzer
Der Nutzer erstellt einen Druckauftrag. 

==== Uni-Druckerei
Die Uni-Druckerei kann den Druckauftrag widerrufen, den der Nutzer in Auftrag gegeben hat. 

==== System
Im System wird der Auftrag unwiderruflich gelöscht.

=== Vorbedingungen
* Nutzer hat einen Druckauftrag generiert 
* Uni-Druckerei möchte den Auftrag stornieren
* Auftrag ist noch nicht mit anderen Druckaufträgen zusammengefasst worden


=== Standardablauf (Basic Flow)
. Der Use Case beginnt, wenn die Uni-Druckerei sich dazu entschließt, den Auftrag zu stornieren.
. Das System zeigt alle in Auftrag gegebene Druckaufträge an.
. Die Uni-Druckerei wählt den zu stornierenden Auftrag aus und löscht diesen.
. Der Auftrag wird unwiderruflich aus dem System gelöscht.
. Das System schließt das Dialogfenster. 
. Das System sendet eine E-Mail an den betreffenden Nutzer und informiert ihn über die Stornierung seines Druckauftrags durch die Uni-Druckerei. 
. Der Use Case ist abgeschlossen. 


=== Alternative Abläufe
==== Abbruch der Stornierung 
Wenn die UNIdruckerei sich vor Schritt 3 entscheidet einen Druckauftrag doch nicht zu stornieren und den Vorgang abbricht.

==== Stornierung durch Nutzer
Siehe Use Case 7.

=== Unterabläufe (Sub Flow)
1. Zusammenführung der Druckaufträge findet ohne den stornierten Druckauftrag statt.



=== Wesentliche Szenarios
==== UNIdruckerei storniert Druckauftrag
Sc1: Die UNIdruckerei storniert den Druckauftrag erfolgreich und eine E-Mail wird erfolgreich an den Nutzer verschickt. Die Bearbeitung der Druckaufträge läuft normal weiter.
Sc2: Die UNIdruckerei storniert den Druckauftrag erfolgreich. Das System sendet unerfolgreich eine E-Mail an den Nutzer. Die Bearbeitung der verbleibenden Druckaufträge läuft normal weiter.

==== Abbruch der Stornierung 
Sc3: Die UNIdruckerei entscheidet sich den entsprechenden Druckauftrag doch nicht zu stornieren und der Druckauftrag wird normal weiterbearbeitet.

=== Nachbedingungen
* Die verbleibenden Druckaufträge werden normal weiterbearbeitet.
* Der stornierte Druckauftrag ist nicht mehr im System aufzufinden.
