= Opal-Druckservice: System-Wide Requirements Specification
Team
:toc: 
:toc-title: Inhaltsverzeichnis
:sectnums:
:icons: font

== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt Workflowergänzung zum OPAL-Druckauftrag spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie 
* zusätzliche Anforderungen (+) für technische, rechtliche und organisatorische Randbedingungen







== Systemweite funktionale Anforderungen
*NFAF-1 Die Authentifizierung erfolgt über den HTW-Login.*

Zur Überprüfung wird ein Testbetrieb eingerichtet.
(relevant für: <<2_usecase_Zugriff_auf_das_Kundenkonto.adoc#,UC2>>)

*NFAF-2 Der Admin soll einen höheren Rechtezugriff haben.*

Zur Überprüfung wird der Zugriff auf das Adminkonto mit dem eines normalen Nutzers verglichen.





== Qualitätsanforderungen für das Gesamtsystem
=== Benutzbarkeit (Usability)
*NFAU-1 Die E-mail-mitteilungen an die Studierenden müssen eindeutig verständlich sein*

Zur Überprüfung werden E-Mails an Testpersonen versendet.
(relevant für: <<1_usceace_Kundenkonto_erstellen.adoc#,UC1>>)

*NFAU-2 Der Anbieter und die Kunden sollen innerhalb von einer Minute den Druck stornieren können.*

Zur Überprüfung wird eine Zeitmessung mit einem Entwickler durchgeführt. (relevant für: <<Usecases\6_usecase_Druck_bestaetigen.adoc#,UC6>>, <<Usecases\7_usecase_Abholung_bestaetigen.adoc#,UC7>>)

*NFAU-3 Der Nutzer soll innerhalb von einer Minute die Auftragsverfolgung einsehen können.*

Zur Überprüfung wird eine Zeitmessung mit einem Entwickler durchgeführt. 


*NFAU-4 Eine Stornierung muss von einem durchschnittlichen Internetnutzer ohne Anleitung durchführbar sein.*

Zur Überprüfung wird eine Stornierung von einer Testperson durchgeführt.





=== Zuverlässigkeit (Reliability)

*NFAR-1 Das System soll nach einer Stornierung den Auftrag aus der Auftragsverfolgung als storniert gekennzeichnet werden.*

Zur Überprüfung wird eine Stornierung von einer Testperson durchgeführt.



    



=== Effizienz (Performance)
*NFAP-1 Das System muss bis zu 10 Nutzern gleichzeitig den Zugriff auf das Kundenkonto ermöglichen können.*

Zur Überprüfung werden sowohl Entwickler, als auch Mitarbeiter der UNI-Druckerei gleichzeitig auf Ihre Kundenkonten zugreifen. 
(relevant für: <<2_usecase_Zugriff_auf_das_Kundenkonto.adoc#,UC2>>)

*NFAP-2 Zeitaufwand Sofortgenerierung*

*NFAP-3 Zeitaufwand Stornierung*






=== Wartbarkeit (Supportability)

*NFAS-1 Das System soll die Anmeldung der HTW-Dresden nutzen können.*

Zur Überprüfung wird ein Testbetrieb eingerichtet.

*NFAS-2 Die Erweiterungen müssen kompatibel mit dem bestehenden System sein.*

Zur Überprüfung wird ein Testbetrieb eingerichtet.

*NFAS-3 Das System soll zusätzliche Einbindungen von Rabattstufen ermöglichen.*

Zur Überprüfung wird testweise eine weitere Rabattstufe hinzugefügt. (relevant für: <<7_usecase_Rabattierung_modifizieren.adoc#,UC7>>)


*NFAS-4 Das System soll für den Administrator verständlich dokumentiert sein.*

Zur Überprüfung wird der Code einschließlich Dokumentation dem Administrator vorgelegt und dieser zum Verständnis befragt.







== Zusätzliche Anforderungen
=== Interfaces

*NFAI-1 Das System muss für verschiedene Bildschirmgrößen nutzbar sein.*

Zur Überprüfung wird ein Testbetrieb eingerichtet.

*NFAI-2 Das System muss auf den gängigen Browsern Google Chrome und Mozilla Firefox lauffähig sein.*

Zur Überprüfung wird ein Testbetrieb eingerichtet.

=== Business Rules

*NFABR-1 Die Stornierung ist nur möglich, solange das Dokument noch nicht gedruckt wurde.*

Zur Überprüfung wird ein Testbetrieb eingerichtet.